// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb1W5420-FcN5Hy82bxdH2GOYhTuYz5Jg',
    appId: '1:305724355081:web:94c17356de7ee525bc3ed8',
    messagingSenderId: '305724355081',
    projectId: 'chat-app-7d727',
    authDomain: 'chat-app-7d727.firebaseapp.com',
    storageBucket: 'chat-app-7d727.appspot.com',
    measurementId: 'G-6V2NFKNBZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ksfDpehDRaWAZeSCgaJyx47AS_Ho2Pw',
    appId: '1:305724355081:android:d51347a92e0da1f8bc3ed8',
    messagingSenderId: '305724355081',
    projectId: 'chat-app-7d727',
    storageBucket: 'chat-app-7d727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvmZz-RMuhpfabh08TubsAmrxpr2WwOk4',
    appId: '1:305724355081:ios:d383ba848751eaa0bc3ed8',
    messagingSenderId: '305724355081',
    projectId: 'chat-app-7d727',
    storageBucket: 'chat-app-7d727.appspot.com',
    iosClientId: '305724355081-pnci3hk1au89tglh5b6kt4ksglgti0os.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvmZz-RMuhpfabh08TubsAmrxpr2WwOk4',
    appId: '1:305724355081:ios:5b8ded095283dbe5bc3ed8',
    messagingSenderId: '305724355081',
    projectId: 'chat-app-7d727',
    storageBucket: 'chat-app-7d727.appspot.com',
    iosClientId: '305724355081-nh5q8mu0gq6u3nehsk7vqeue6haasqoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
